### ISSUE TITLE
[Example Rule Issue] failing to find feed on BitChute

### ISSUE THREAD

**Issue by atomGit** [igorlogius/list-feeds#11]
Linux, Firefox 103.*, List Feeds 1.9.15

for BitChute the channel URL is detected instead of the feed URL

ex. https://www.bitchute.com/channel/ThhX40cqlo78/

for reference, the template for BitChute:

`https://www.bitchute.com/feeds/rss/channel/<channel_name>`

note that the channel name is needed - the channel ID won't work - for the example above the channel name is 'corbettreportextras'

also you might consider adding `/?showall=1` to the feed URL since BitChute may censor some results without it

**Comment by igorlogius** [comment]
I made some change to the `custom-feed-detectors.json` maybe it works better like this, but no promises.

**Comment by igorlogius** [comment]
Might be that my way of building the

**Comment by atomGit** [comment]
the 1.9.16 update now detects the embed url:

ex. page: https://www.bitchute.com/video/JFNU8Pr1pNE2/

`https://www.bitchute.com/oembed/?url=https://www.bitchute.com/video/JFNU8Pr1pNE2/&format=json`

**Comment by atomGit** [comment]
if it helps, [Feedbro](https://addons.mozilla.org/en-US/firefox/addon/feedbroreader/) apparently handles BitChute - i'm not much of a coder at all, but it looks like the parser is in the feedbro.min.js file beginning around line 7366

**Comment by igorlogius** [comment]
@atomGit 

Using this detection snippet 
```
const feeds = [];
let feedUrl;
const url = new URL(window.location.href);
const parts = url.pathname.split('/');
if(parts.length > 1) {
  let channelname = '';
  switch(parts[1]) {
    case  'channel': 
    case 'video':
        const channelname_selector = 'div.channel-banner > div.details > p.name > a:nth-child(1)'
        channelname = document.querySelector(channelname_selector).href.split('/channel/')[1];      
        break;
   }
   if(channelname !== '') {
        feedUrl = new URL('/feeds/rss/channel/' + channelname + '?showall=1',url.origin);                                                               
        feeds.push(feedUrl.toString());
   }
}
return feeds;
```

My addons wins 3 to 1 against feedbro. 

| | channel name| channel id  | video |
| -  | -| - | - |
| list-feeds | :heavy_check_mark: |:heavy_check_mark:| :heavy_check_mark:  |
| feedbro | :heavy_check_mark: | :no_entry:   | :no_entry:   |


## Result Screenshots

### List Feed '/channel' with name (OK) 
![snip_20220910-170215](https://user-images.githubusercontent.com/67047467/189489244-c6b10781-3368-4032-8b55-77d06800f562.png)

### List Feed '/channel' with id (OK) 
![snip_20220910-170316](https://user-images.githubusercontent.com/67047467/189489268-e6a57242-e6e6-45f9-b43f-f8bd3daad27a.png)

### List Feed '/video'  (OK) 
![snip_20220910-170359](https://user-images.githubusercontent.com/67047467/189489296-c3eeae8b-c97e-44e2-9d7d-d875129ce929.png)

### Feedbro '/channel' with name  (OK)
![snip_20220910-165839](https://user-images.githubusercontent.com/67047467/189489054-0cd3a7f6-b144-4d5a-a6d3-f82ff9f97601.png)

### Feedbro '/channel'  with id  (FAIL) 
![snip_20220910-170026](https://user-images.githubusercontent.com/67047467/189489152-1859b776-b175-428d-8162-f41f05ff481e.png)

### Feedbro '/video' (FAIL) 
![snip_20220910-164621](https://user-images.githubusercontent.com/67047467/189489170-8cba49ec-0316-4048-94e6-59d71957948b.png)

**Comment by atomGit** [comment]
it's not working for me on a fresh profile with *.16 version

no feeds found...

![lf1](https://user-images.githubusercontent.com/1817307/189490295-d358c0cc-f089-403d-b77b-b561b21c5146.png)

incorrect link...

![lf2](https://user-images.githubusercontent.com/1817307/189490296-2965b7ca-6c5b-44a2-ba76-4537e556c572.png)

**Comment by igorlogius** [comment]
@atomGit  
What you show ... looks like when the rules is not correctly imported. 
I just updated the custom-feed-detectors.json
Please try importing that. 
Might have been a simple copy and paste error .

**Comment by atomGit** [comment]
the new json rules work, just some minor issues...

* when i first loaded `https://www.bitchute.com/channel/ThhX40cqlo78/` no feeds were detected until i F5'd it - this may be a bitchute issue and is no big deal
* on a video page `https://www.bitchute.com/video/d0XI05h8FmQ/`  2 feeds are detected - one is the correct channel feed and the other is the embed URL `https://www.bitchute.com/oembed/?url=https://www.bitchute.com/video/d0XI05h8FmQ/&format=json` - perhaps that's due to me importing the json file and maybe the import and the default rules are both in play

**Comment by igorlogius** [comment]
@atomGit  yeah, the default rules always look for feeds of type `xml` or `json`, 
but i could add a switch to each rule which disabled the default detection mechanic

**Comment by igorlogius** [comment]
#15

**Comment by atomGit** [comment]
no need to add a switch on my account - i'm ok with the way it is

**Comment by igorlogius** [comment]
@atomGit 
Well, then ... i wont add it on your account, but purely out of my own selfishness ;)  

`exclusion regex` with it you can filter out stuff you dont want to see. - Like json,  embeds  and so on.

**Comment by atomGit** [comment]
thanks for addressing these issues ;)
