### ISSUE TITLE
unable to enable pageAction icon

### ISSUE THREAD

**Issue by atomGit** [igorlogius/list-feeds#28]
first of all, thanks again for working on this extension :)

i can't get the pageAction icon working

the description on the details tab in about:addons says...

> To display the pageAction icon, when a feed is found, the addon requires an addional permission, which can be enabled via the preference page.

this seems to suggest that a new option will be found on the options.html page, but there isn't (it's exactly the same as before), so i checked the add-on permissions and there is nothing new there either, just 'Access your data for all websites'

( btw, 'addional' should be additional ) 

* i tested with a fresh profile
* installed the add-on
* loaded different pages where LF detected a feed
* checked both the aboiut:addons > permission tab and the options.html page for an option to enable a new permission, but nothing is there

PC, Linux, FF 104.*, LF 1.13.16

**Comment by igorlogius** [comment]
@atomGit  
Thank you for letting me know. 

This is totally my fault. I did not keep up with updating the addon description. 
I intentionally switched from using the pageAction to using the browserAction. 
From what i have seen it seems that browserAction is becoming the prefered method. 
I personally also liked the pageAction but there is a certain consistency to always show the icon and just change its color/status to indicate something.  AFAIK, Mobile also only supports browserActions ... so thats a bonus too.

The permission stuff is something i've been fight with myself over, i opted to include the <all_urls> (Access to all Websites) which makes this addon more userfriendly by "normal" users. Initally i though that the feed detection should only be runable on a useraction, but that would disable the indicator function of the addon (if a feed is available) That is why  i choose to include the permission ... still not 100% sure if that decision was the best to make. 

Thanks again for the heads up. 
I'll update the description to match the current addon functions/behaviour asap. 

PS: 
For the future i plan to have the addon description in the repository, which just as the releases will get pushed/synced to AMO. I'll only have to find the time and motivation to finally read the AMO API documentation and find out how todo this and then actually add this to the current github workflow. :dizzy:

**Comment by atomGit** [comment]
re: permissions - can LF be detected by the server? 

if not, then i'm perfectly fine with the current access permission

if so, then i'm not sure what to think about this - while i don't like the idea of adding a fingerprint metric, i also like the convince of auto-changing icon states

as for page vs. browser action, i prefer the former - i just think it's a bit more intuitive and it saves on toolbar space ... so ... if you feel like it :) i might suggest adding an option to toggle page/browser action (with the default probably best set to browser action for the reason you mentioned regarding mobile)

**Comment by igorlogius** [comment]
>  can LF be detected by the server?
No. The server can not reliably detect LF. It can only heuristically make an educated guess if but i can not be sure, since LF HEAD requests look exactly like any other browser request to these endpoints. 

>   as for page vs. browser action, i prefer the former
I'll see if i can in a reasonable manner add an option to switch to the pageAction display.

**Comment by igorlogius** [comment]
The toolbar icon can be removed by the user via the "Customize Toolbar..." context menu. 

Since i improved the addon so it doesnt re-send the requests multiple times, i now can not use the old mechanic, but i'll see to re-incorporate the pageAction via a switch on the option page.

**Comment by igorlogius** [comment]
@atomGit 
Version 1.14.16 now has a checkbox on the option page to enable the pageAction.  
You have to remove/hide the toolbar icon yourself, via "Customize Toolbar..." context menu. 
Hope this works for you.

**Comment by igorlogius** [comment]
![snip_20220922-214952](https://user-images.githubusercontent.com/67047467/191838090-27876273-7005-4438-a955-e2c53f0c53da.png)
![snip_20220922-220128](https://user-images.githubusercontent.com/67047467/191840040-65eb88a8-7de4-4f89-b241-fee359d4f751.png)

**Comment by atomGit** [comment]
great - thanks again!

cheers
