### ISSUE TITLE
odysee feed detection

### ISSUE THREAD

**Issue by atomGit** [igorlogius/list-feeds#29]
LF uses lbryfeed.melroy.org for odysee/LBRY feeds (i believe that was a result of my suggestion) however he shut down the service because the platform now publishes feeds (without having to pay for a membership) - the feeds are not detected by LF however

the feed button is the 3-dot drop menu near the top right of a channel page

example feed: `https://odysee.com/$/rss/@corbettreport:0`

how or where the feed URLs are generated i don't know, but they are not listed in the page source 

https://lbry.com/i18n/get/lbry-desktop/app-strings/en.json lists the strings (Copy RSS URL, etc.), but not the URLs

**Comment by igorlogius** [comment]
I'll take a look.

**Comment by igorlogius** [comment]
Well, this 

```
const feeds = [];
let feedUrl;
const url = new URL(window.location.href);

const parts = url.pathname.split('/');
if(parts.length > 1) {
	const channelname = parts[1];
	if(channelname.startsWith('@')) {
		if(channelname !== '') {
			feeds.push(url.origin + '/$/rss/' + channelname);
		}
	}
}
return feeds;
```

seems to work. 

I'll update the `custom-feed-example.json` later.
