### ISSUE TITLE
templates for video sites...

### ISSUE THREAD

**Issue by atomGit** [igorlogius/list-feeds#3]
here's a few templates for some other sites if interested...

```
BitChute: https://www.bitchute.com/feeds/rss/channel/<channel_name>
LBRY/Oddesy: https://lbryfeed.melroy.org/channel/<channel_name>
Steemit: http://www.hiverss.com/@<channel_name>/feed
Vimeo: https://vimeo.com/<channel_name>/videos/rss
```

**Comment by igorlogius** [comment]
Thanks for the info. 
If the feeds aren't yet directly exposed by the sites, i'll check if i can add them.

**Comment by igorlogius** [comment]
bitchute and vimeo are done.
But for lbryfeed and hiverss i'll have to take a closer look.
Both as far as i can tell seem to be meta services which are not directly provided by the sites themself. 
I am not sure if adding/using them is a very good idea. 
But i'll think about it.

**Comment by igorlogius** [comment]
Some feeds are now added, there might be some missing. 
I'll be waiting for the bug reports. 
Later.

**Comment by atomGit** [comment]
the Steemit one was a poor suggestion on my part since the feed is built by a 3rd party (hiverss.com) - vimeo and bitchute were the more important ones ... thanks!
