### ISSUE TITLE
feed detector for Odysee

### ISSUE THREAD

**Issue by atomGit** [igorlogius/list-feeds#36]
**Describe the bug**
feed detector for Odysee seems broken

**To Reproduce**
channel: https://odysee.com/@drsambailey:c
feed: https://odysee.com/$/rss/@drsambailey:c

**Desktop (please complete the following information):**
linux
firefox v115
list-feeds v1.17.42
using the latest custom-feed-detectors.json

i don't know squat about JS, but the detection code seems ok to me other than there *might* be an extra line??? - this is off topic of course, but if you're already testing if channelname starts with '@', then is it necessary to then test if it's empty?

```js
    if (channelname.startsWith("@")) {
      if (channelname !== "") {
        feeds.push(url.origin + "/$/rss/" + channelname);
      }
    }
```

**Comment by igorlogius** [comment]
1. You are right, the `if(channelname !== "") {` definitely is not necessary. I'll fix that asap. Thanks for taking a close look. 

2. About the bug, i have to admit, that i dont quite see the issue. 

When i click 
![snip_20230718-160519](https://github.com/igorlogius/list-feeds/assets/67047467/c87fc8fa-6ea0-48da-a828-63904ec00622)

i get `https://odysee.com/$/rss/@drsambailey:c`  copied into my clipboard, 
which is the same url i see in the feed list 

![snip_20230718-160748](https://github.com/igorlogius/list-feeds/assets/67047467/e8135b96-5922-4f42-a82b-4999e4ebe13c)

And as far as i can tell, it correctly loads the feed xml.

![Screenshot_2023-07-18_16-13-14](https://github.com/igorlogius/list-feeds/assets/67047467/64720ed4-a87b-42b3-a797-8ab70f52f096)

That the url with the `:c` might look strange but AFAIK it isnt an error or illegal.

**Comment by atomGit** [comment]
it works for me now too - funny, because i tried it several times using different channel page URLs and the LF icon never appeared in the address bar despite the page being fully loaded (so far as i know)

glitch in the matrix?

i'll let you close this due to the code issue

**Comment by igorlogius** [comment]
> i'll let you close this due to the code issue

generous ;) thanks
