### ISSUE TITLE
visual indication

### ISSUE THREAD

**Issue by atomGit** [igorlogius/list-feeds#4]
there should probably be a visual indication when feeds are found, as in a change in the icon - better yet, i might suggest placing the icon in the address bar and hiding it when inactive

**Comment by igorlogius** [comment]
You might want to take a look at  `detect-feeds`
https://addons.mozilla.org/en-US/firefox/addon/detect-feeds/

Hope it helps.

**Comment by atomGit** [comment]
now that i understand the diff between the 2 extensions, i'll close this
