### ISSUE TITLE
'link[rel*="alternate"]' seems to be way too strong assumption

### ISSUE THREAD

**Issue by shenlebantongying** [igorlogius/list-feeds#6]
https://github.com/igorlogius/list-feeds/blob/3f39814d19a13d5373fddc7d9f60a00b4e8112f1/content-script.js#L8

I might be wrong about JavaScript, but if I understand correctly, this requires the link to RSS/atom to looks like
```
<link rel="alternate" href="https://www.example.com/" />
```

However, I have encountered a lot of people just throw a plain `<link href="/rss.xml">` link to their website and nothing more. Using `rel="alternate"` is for sure more "standard", but not everyone knows that.

**Comment by shenlebantongying** [comment]
The one used by livemarks seems to be better
https://github.com/nt1m/livemarks/blob/82666a51a53e7c6b2186b38789217b2998105808/contentscripts/feed_finder.js#L14-L17

**Comment by igorlogius** [comment]
I like standards, but i can see that many websites would not add the 'alternate' attribute 
Although this will reduce the accuarcy but i guess that is not a huge dealbreaker.  

The livemark xpath ... is nice ... but a little to "generous" for my taste. 
I would expect a page to at least partially correctly identify a link with a mimetype. 

I'll see what i can do.

**Comment by igorlogius** [comment]
fixed in version 1.7.7
