### ISSUE TITLE
[Improvement Suggestion] use a more traditional toolbar and pageAction icon

### ISSUE THREAD

**Issue by atomGit** [igorlogius/list-feeds#8]
mainly stopped by to say thanks, but also to consider changing the icon to a [more traditional RSS type](https://rss.com/blog/wp-content/uploads/2019/10/social_style_3_rss-512-1.png)

the current icon reminds me of a note/text editor :)

and thanks again for adding bitchute, vimeo, etc. - i see it also works for old.reddit.com which is great

i also like that, when the permission "Access your data for all websites" is enabled, it appears that nothing is being injected into the page

**Comment by igorlogius** [comment]
> ... consider changing the icon to a more traditional RSS type
well, i guess the main advantage would be that a user could more easily recognice the function ... 
i just kind of dont like to use  "stock"  icons ... but maybe you are right... 

> the current icon reminds me of a note/text editor :)
sorry, i am no very good with picture editing software.   
I mostly just try to ... create my own stuff ... to not infringe on any copyright(s) 

> and thanks again for adding bitchute, vimeo, etc. 
No problem.  Glad i could help out. 

> when the permission "Access your data for all websites" is enabled, it appears that nothing is being injected into the page
If you mean  "not enabled", then yes  you are correct. 
The detection script injection is only done when the toolbar icon is actively clicked by the user in that case. 
It's the privacy friendliest (and laziest aka. best)  solution i could find. Glad you like it.  :-) 

Have a good one.
